title: "Work Portfolio Abdul Mateen"
author: "Abdul Mateen"
description: "University of Warsaw - J P Morgan Chase"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true         # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "home.html", title: "Home Page", icon: home}
  - {file: "README.md", title: "About me", icon: About me}
  - {file: "https://github.com/khuwajamat/khuwajamat.github.io/blob/master/_posts/stock_price_prediction.md", title: "Stock Price Prediction"}
  - {file: "https://github.com/khuwajamat/khuwajamat.github.io/blob/master/_posts/newborns_ML_Final_project.md", title: "Machine_Learning_Analysis_newborns"}
  - {file: "https://github.com/khuwajamat/khuwajamat.github.io/blob/master/_posts/2023-02-05-Economic_aspects_of_immigrants.md", title: "Economic_aspects_of_Migration"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:mateenabdul020@gmail.com"}
  - {title: Linkedin, icon: github, url: "https://www.linkedin.com/in/abdul-mateen-aa1a2ab6/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
